#!/bin/bash

PROJECT_DIR=$PWD
INC_DIR=$PWD/PCMC_lib/include

#export PROJECT_DIR


CPLUS_INCLUDE_PATH=$INC_DIR/Energy$CPLUS_INCLUDE_PATH;
shift 1;
CPLUS_INCLUDE_PATH=$INC_DIR/Random$CPLUS_INCLUDE_PATH;
echo $CPLUS_INCLUDE_PATH
#echo $IFS
#export CPLUS_INCLUDE_PATH